server:
  port: 8080

jira:
  source:
    base-url: ${env.JIRA_SOURCE_BASE_URL:}
    data-folder: ${env.JIRA_SOURCE_DATA_FOLDER:}
    email: ${env.JIRA_SOURCE_EMAIL:}
    authToken: ${env.JIRA_SOURCE_AUTHTOKEN:}
    bearerToken: ${env.JIRA_SOURCE_BEARERTOKEN:}
    mapping-config: "classpath:jira-mapping-source.yml"

  destination:
    base-url: ${env.JIRA_DESTINATION_BASE_URL:}
    data-folder: ${env.JIRA_DESTINATION_DATA_FOLDER:}
    email: ${env.JIRA_DESTINATION_EMAIL:}
    authToken: ${env.JIRA_DESTINATION_AUTHTOKEN:}
    bearerToken: ${env.JIRA_DESTINATION_BEARERTOKEN:}
    mapping-config: "classpath:jira-mapping-destination.yml"

servicenow:
  instanceUrl: ${SERVICENOW_INSTANCE_URL:}
  username: ${SERVICENOW_USERNAME:}
  password: ${SERVICENOW_PASSWORD:}

confluence:
  instanceUrl: ${CONFLUENCE_INSTANCE_URL:}
  username: ${CONFLUENCE_USERNAME:}
  apiToken: ${CONFLUENCE_API_TOKEN:}

logging:
  level:
    root: INFO
