server:
  port: 8080

jira:
  source:
    base-url: ""
    email: ""
    authToken: ""
    bearerToken: ""
    mapping-config: "classpath:jira-mappings-source.yml"

  destination:
    base-url: ""
    email: ""
    authToken: ""
    bearerToken: ""
    mapping-config: "classpath:jira-mappings-destination.yml"

logging:
  level:
    root: INFO